/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:2be70330-6383-4d42-8143-58c2e73278b7",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_oYcxNR2FK",
    "aws_user_pools_web_client_id": "7pl6ha9rvld26jthh5aog4akn0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://lh2x26oidrfvje4irmceo6cho4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wfgzdfb2sfbfxfgheihr7eg24m"
};


export default awsmobile;
